### PR TITLE
italian translation

### PR DESCRIPTION
**Pull request by bacchilega**
Traduzione in italiano di PD Runner

### CODE REVIEW

**Comment by bacchilega** [comment]
this is the italian translation :)

**Comment by lihaoyun6** [comment]
@bacchilega 
Thank you for your support, but it seems that this translation is missing some lines.  
Are you sure you are using the latest version of the `base.strings` file instead of an earlier version?

**Comment by bacchilega** [comment]
Hello lihaoyun, it's a pleasure to help you. 
Yes i've been using the german translation model, sorry.
Now I have updated the translation

**Comment by bacchilega** [comment]
is that okay?

**Pull request merged**
