### PR TITLE
pt_BR.string

### PR DESCRIPTION
**Pull request by slipttees**
Translation to Portuguese Brazil!

### CODE REVIEW

**Comment by lihaoyun6** [comment]
Thanks, and I'm sorry. I forgot to include "about panel" in the string file (now it has been added).
Please complete these parts, and then I will use them in the new version of PD Runner.

**Comment by slipttees** [comment]
Okay Dude!

**Comment by lihaoyun6** [comment]
@slipttees Thank you for your support.
PD Runner [v0.2.10](https://github.com/lihaoyun6/PD-Runner/releases/tag/0.2.10) has been released with Portuguese(Brazil) translation.
Xnip2021-11-30_03-42-28

**Comment by lihaoyun6** [comment]
@slipttees 
I have updated the `base.strings` file and added lines [48](https://github.com/lihaoyun6/PD-Runner/blob/main/localization/base.strings#L48) and [49](https://github.com/lihaoyun6/PD-Runner/blob/main/localization/base.strings#L49).   
Can you help me to complete the translation of these lines?  
Thank you.

**Pull request merged**
